<?php

namespace AppBundle\Repository;

/**
 * ApiSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
