<?php

namespace AppBundle\Repository;

/**
 * ListingProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingProductRepository extends \Doctrine\ORM\EntityRepository
{
}
