<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingProductRepository extends EntityRepository
{
    public function removeExcludedListingProducts($listingId, $productsIds)
    {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:ListingProduct lp
                  WHERE lp.listing = :listing AND
                  lp.product NOT IN ( :products )'
            )
            ->setParameters(array('listing' => $listingId, 'products' => $productsIds))
            ->getResult();
    }
}
