<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends \Doctrine\ORM\EntityRepository
{
    public function countListingsByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(l.id) AS listings, l.createdAt 
                  FROM AppBundle:Listing l
                  WHERE l.deleted = 0
                  GROUP BY l.createdAt 
                  ORDER BY l.createdAt ASC'
            )
            ->getResult();

    }
}
