<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends EntityRepository
{
    public function countListingsByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(l.id) AS listings, l.createdAt, YEAR(l.createdAt) AS y,
                  MONTH(l.createdAt) AS m, DAY(l.createdAt) AS d
                  FROM AppBundle:Listing l
                  WHERE l.deleted = 0
                  GROUP BY y, m, d 
                  ORDER BY l.createdAt ASC'
            )
            ->getResult();

    }

    public function findByDate($date)
    {
        $date = explode('-', $date);
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l
                  FROM AppBundle:Listing l
                  WHERE l.deleted = 0
                  AND YEAR(l.createdAt) = :y
                  AND MONTH(l.createdAt) = :m
                  AND DAY(l.createdAt) = :d'
            )
            ->setParameters(array('y' => $date[0], 'm' => $date[1], 'd' => $date[2]))
            ->getResult();

    }
}
