<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingProductRepository extends EntityRepository
{
    public function removeExcludedListingProducts($listingId, $productsIds)
    {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:ListingProduct lp
                  WHERE lp.listing = :listing AND
                  lp.product NOT IN ( :products )'
            )
            ->setParameters(array('listing' => $listingId, 'products' => $productsIds))
            ->getResult();
    }

    public function findProductsByListings($listingIds)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                      FROM AppBundle:Product p
                      WHERE p.deleted = 0 AND p.id IN (
                        SELECT IDENTITY(lp.product)
                        FROM AppBundle:ListingProduct lp
                        WHERE lp.listing IN ( :listings )
                      )'
            )
            ->setParameters(array('listings' => $listingIds))
            ->getResult();
    }
}
