<?php

namespace AppBundle\Repository;

/**
 * MartinsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MartinsOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
