<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function countProductByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p.createdAt) AS quantity, p.createdAt 
                  FROM AppBundle:Product p 
                  WHERE p.deleted = 0 
                  GROUP BY p.createdAt 
                  ORDER BY p.createdAt ASC'
            )
            ->getResult();

    }

    public function productWithMinPrice()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, (
                    SELECT MIN(qs.price)
                    FROM AppBundle:QuoteSupplier qs
                    WHERE qs.quoteProduct IN (
                      SELECT qp.id
                      FROM AppBundle:QuoteProduct qp
                      WHERE qp.product = p.id
                    ) 
                  ) AS minPrice
                  FROM AppBundle:Product p 
                  WHERE p.deleted = 0 
                  GROUP BY p.createdAt 
                  ORDER BY p.createdAt ASC'
            )
            ->getResult();

    }
}
