<?php

namespace AppBundle\Repository;

/**
 * QuoteProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProductRepository extends \Doctrine\ORM\EntityRepository
{
}
