<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function countActives()
    {
        return count($this->getActives());
    }

    public function getActives()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q
                  FROM AppBundle:Quote q
                  WHERE q.expiresAt > CURRENT_TIMESTAMP()'
            )
            ->getResult();
    }

}
