<?php

namespace AppBundle\Repository;

/**
 * QuoteSupplierStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteSupplierStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
