<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteSupplierRepository extends EntityRepository
{

    /**
     * @param $id
     * @return array
     */
    public function getQuotesAverage($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT (SUM(qs.price) / COUNT(qs)) AS average 
                  FROM AppBundle:QuoteSupplier qs
                  WHERE qs.deleted = 0 AND qs.price > 0 
                  AND qs.quoteProduct IN (
                    SELECT qp 
                    FROM AppBundle:QuoteProduct qp
                    WHERE qp.deleted = 0 
                    AND qp.quote IN (
                      SELECT q
                      FROM AppBundle:Quote q
                      WHERE q.retailer = :id
                    )
                  )'
            )
            ->setParameters(array('id' => $id))
            ->setMaxResults(1)
            ->getResult();
    }

}
