<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function countActives()
    {
        return count($this->getInProgress());
    }

    public function getInProgress()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q
                  FROM AppBundle:Quote q
                  WHERE q.expiresAt > CURRENT_TIMESTAMP() AND q.deleted = 0'
            )
            ->getResult();
    }

    public function getEnded()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q
                  FROM AppBundle:Quote q
                  WHERE q.expiresAt < CURRENT_TIMESTAMP() AND q.deleted = 0'
            )
            ->getResult();
    }

    public function getQuoteByRepresentative($email, $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q
                  FROM AppBundle:Quote q
                  WHERE q.id = :id
                  AND q.deleted = 0
                  AND q.retailer IN (
                    SELECT IDENTITY(r.retailer)
                    FROM AppBundle:Representative r
                    WHERE r.email = :email
                    AND r.deleted = 0
                  )'
            )
            ->setParameters(array('id' => $id, 'email' => $email))
            ->setMaxResults(1)
            ->getResult();
    }

    public function countQuotesByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(q.id) AS quotes, q.createdAt, YEAR(q.createdAt) AS y,
                  MONTH(q.createdAt) AS m, DAY(q.createdAt) as d
                  FROM AppBundle:Quote q
                  WHERE q.deleted = 0
                  GROUP BY y, m, d
                  ORDER BY q.createdAt ASC'
            )
            ->getResult();
    }

}
