<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteProductRepository extends EntityRepository
{
    public function removeExcludedQuoteProducts($quoteId, $productsIds)
    {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:QuoteProduct qp
                  WHERE qp.quote = :quote AND
                  qp.product NOT IN ( :products )'
            )
            ->setParameters(array('quote' => $quoteId, 'products' => $productsIds))
            ->getResult();
    }
}
