<?php

namespace AppBundle\Repository;

/**
 * QuoteSupplierHasQuoteProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteSupplierHasQuoteProductRepository extends \Doctrine\ORM\EntityRepository
{
}
