<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function countSupplierByRegion()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.name, 
                  (SELECT COUNT(DISTINCT (s.cnpj))
                    FROM AppBundle:Supplier s
                    WHERE s.deleted = 0
                    AND s.state IN (
                      SELECT st
                      FROM AppBundle:State st
                      WHERE st.region = r.id
                    )  
                  ) AS y
                  FROM AppBundle:Region r  
                  GROUP BY r.id HAVING y > 0'
            )
            ->getResult();

    }

    public function countRetailerByRegion()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT rg.name, 
                  (SELECT COUNT(re.id)
                  FROM AppBundle:Retailer re
                  WHERE re.deleted = 0 AND re.verified = 1
                  AND re.state IN (
                    SELECT st
                    FROM AppBundle:State st
                    WHERE st.region = rg.id
                    )
                  ) AS y
                  FROM AppBundle:Region rg  
                  GROUP BY rg.id HAVING y > 0'
            )
            ->getResult();

    }
}
