<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativeRepository extends EntityRepository
{
    public function getRepresentativeByQuote($email, $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r
                  FROM AppBundle:Representative r
                  WHERE r.email = :email
                  AND r.deleted = 0
                  AND r.retailer IN (
                    SELECT IDENTITY(q.retailer)
                    FROM AppBundle:Quote q
                    WHERE q.id = :id
                  )'
            )
            ->setParameters(array('id' => $id, 'email' => $email))
            ->setMaxResults(1)
            ->getResult();
    }
}
