<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerRepository extends EntityRepository
{
    public function countClientByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(r.createdAt) AS clientes, r.createdAt FROM AppBundle:Retailer r GROUP BY r.createdAt ORDER BY r.createdAt ASC'
            )
            ->getResult();

    }
}
