<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RetailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailerRepository extends EntityRepository
{
    public function countClientByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(r.createdAt) AS clients, YEAR(r.createdAt) AS y, 
                  MONTH(r.createdAt) AS m, DAY(r.createdAt) AS d
                  FROM AppBundle:Retailer r
                  WHERE r.deleted = 0 AND r.verified = 1
                  GROUP BY y, m, d
                  ORDER BY r.createdAt ASC'
            )
            ->getResult();

    }
}
