<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function countSupplierByState()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT st.name, 
                    (SELECT COUNT(DISTINCT (su.cnpj))
                      FROM AppBundle:Supplier su
                      WHERE su.state = st.id AND su.deleted = 0 
                    ) AS y
                  FROM AppBundle:State st 
                  GROUP BY st.id HAVING y > 0'
            )
            ->getResult();

    }

    public function countRetailerByState()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.name, 
                    (SELECT COUNT(r.id)
                      FROM AppBundle:Retailer r
                      WHERE r.state = s.id AND r.deleted = 0
                    ) AS y
                  FROM AppBundle:State s
                  GROUP BY s.id HAVING y > 0'
            )
            ->getResult();
    }
}
