<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends EntityRepository
{
    public function groupByCnpj()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id, s.cnpj, s.name, 
                  (SELECT COUNT(r.id)
                    FROM AppBundle:Representative r
                    WHERE r.supplier IN (
                      SELECT s2.id 
                      FROM AppBundle:Supplier s2
                      WHERE s2.cnpj = s.cnpj 
                    ) 
                  ) AS qtyRepresentatives,
                  (SELECT COUNT(qp.id)
                   FROM AppBundle:QuoteProduct qp
                   WHERE qp.id IN (
                    SELECT qs.id
                    FROM AppBundle:QuoteSupplier qs
                    WHERE qs.representative IN (
                      SELECT r2.id
                      FROM AppBundle:Representative r2
                      WHERE r2.supplier IN (
                        SELECT s3.id 
                        FROM AppBundle:Supplier s3
                        WHERE s3.cnpj = s.cnpj 
                        ) 
                      )
                    ) 
                  ) AS qtyQuotes
                  FROM AppBundle:Supplier s
                  WHERE s.deleted = 0
                  GROUP BY s.cnpj
                  ORDER BY s.createdAt ASC'
            )
            ->getResult();
    }

    public function groupByCnpjAndId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id, s.cnpj, s.name, 
                  (SELECT COUNT(r.id)
                    FROM AppBundle:Representative r
                    WHERE r.supplier IN (
                      SELECT s2.id 
                      FROM AppBundle:Supplier s2
                      WHERE s2.cnpj = s.cnpj 
                    ) 
                  ) AS qtyRepresentatives,
                  (SELECT COUNT(qp.id)
                   FROM AppBundle:QuoteProduct qp
                   WHERE qp.id IN (
                    SELECT qs.id
                    FROM AppBundle:QuoteSupplier qs
                    WHERE qs.representative IN (
                      SELECT r2.id
                      FROM AppBundle:Representative r2
                      WHERE r2.supplier IN (
                        SELECT s3.id 
                        FROM AppBundle:Supplier s3
                        WHERE s3.cnpj = s.cnpj 
                        ) 
                      )
                    ) 
                  ) AS qtyQuotes
                  FROM AppBundle:Supplier s
                  WHERE s.deleted = 0 
                  AND s.cnpj = (
                    SELECT s4.cnpj
                    FROM AppBundle:Supplier s4
                    WHERE s4.id = :id
                  )
                  GROUP BY s.cnpj
                  ORDER BY s.createdAt ASC'
            )
            ->setParameters(array('id' => $id))
            ->getResult();
    }

    public function countSuppliersByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(s.id) AS suppliers, s.createdAt, YEAR(s.createdAt) AS y,
                  MONTH(s.createdAt) AS m, DAY(s.createdAt) as d
                  FROM AppBundle:Supplier s
                  WHERE s.deleted = 0
                  GROUP BY y, m, d
                  ORDER BY s.createdAt ASC'
            )
            ->getResult();
    }

    public function findTopSuppliers()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id, s.cnpj, s.name, 
                  (SELECT COUNT(r.id)
                    FROM AppBundle:Representative r
                    WHERE r.supplier IN (
                      SELECT s2.id 
                      FROM AppBundle:Supplier s2
                      WHERE s2.cnpj = s.cnpj 
                    ) 
                  ) AS qtyRepresentatives,
                  (SELECT COUNT(qp.id)
                   FROM AppBundle:QuoteProduct qp
                   WHERE qp.id IN (
                    SELECT qs.id
                    FROM AppBundle:QuoteSupplier qs
                    WHERE qs.representative IN (
                      SELECT r2.id
                      FROM AppBundle:Representative r2
                      WHERE r2.supplier IN (
                        SELECT s3.id 
                        FROM AppBundle:Supplier s3
                        WHERE s3.cnpj = s.cnpj 
                        ) 
                      )
                    ) 
                  ) AS qtyQuotes
                  FROM AppBundle:Supplier s
                  WHERE s.deleted = 0
                  GROUP BY s.cnpj
                  ORDER BY qtyQuotes DESC'
            )
            ->setMaxResults(10)
            ->getResult();
    }

    public function findSuppliersQuotesAndOrders()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.name, s.cnpj, 
                  (SELECT COUNT(qp.id)
                   FROM AppBundle:QuoteProduct qp
                   WHERE qp.id IN (
                    SELECT qs.id
                    FROM AppBundle:QuoteSupplier qs
                    WHERE qs.representative IN (
                      SELECT r2.id
                      FROM AppBundle:Representative r2
                      WHERE r2.supplier IN (
                        SELECT s3.id 
                        FROM AppBundle:Supplier s3
                        WHERE s3.cnpj = s.cnpj 
                        ) 
                      )
                    ) 
                  ) AS qtyQuotes
                  FROM AppBundle:Supplier s
                  WHERE s.deleted = 0
                  GROUP BY s.cnpj
                  ORDER BY qtyQuotes DESC'
            )
            ->setMaxResults(600)
            ->getResult();
    }
}
