# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\RepresentativeUser: bcrypt
        AppBundle\Entity\Retailer: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, retailer_db_provider, representative_db_provider]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$mTkHBLOSgP/NrSV5Gb5HiOilXbHyBFUsMdVJrA9f7lpFEfr7Rb/6m #admin123
                        roles: 'ROLE_ADMIN'
        representative_db_provider:
            entity:
                class: AppBundle:RepresentativeUser
                property: username
        retailer_db_provider:
            entity:
                class: AppBundle:Retailer
                property: email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|api)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: /login
                check_path: /login

            logout:
                path: /logout
                target: /login

            access_denied_url: /acesso-negado

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/cadastro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/recuperacao-senha, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/administrador, roles: ROLE_ADMIN }
         - { path: ^/varejista, roles: ROLE_USER }
         - { path: ^/representante, roles: ROLE_REPRESENTATIVE }